[tools]
"go" = "latest"
"python" = '3'
"node" = '22'

# npm
"npm:npm" = "latest"
"npm:bash-language-server" = "latest"

# pipx
"pipx:black" = { version = "latest" }
"pipx:python-language-server" = { version = "latest" }

# terraform
"terraform" = "latest"
"terraform-ls" = "latest"

