[tools]
"go" = "latest"
"python" = '3'
"node" = '22'

# npm
"npm:npm" = "latest"
"npm:bash-language-server" = "latest"
"npm:eslint" = "latest"
"npm:prettier" = "latest"
"npm:pyright" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"

# pipx
"pipx:black" = { version = "latest" }

# terraform
"terraform" = "latest"
"terraform-ls" = "latest"

